# Generated by Django 5.0.4 on 2024-05-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tea_Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("black_tea", models.PositiveIntegerField()),
                ("plane_milk_regular", models.PositiveIntegerField()),
                ("zinger_milk_regular", models.PositiveIntegerField()),
                ("cutting_half", models.PositiveIntegerField()),
                ("cutting_full", models.PositiveIntegerField()),
                ("matka_half", models.PositiveIntegerField()),
                ("matka_full", models.PositiveIntegerField()),
                ("lemon_water", models.PositiveIntegerField()),
                ("description", models.TextField()),
            ],
        ),
    ]
