# Generated by Django 5.0.4 on 2024-07-03 09:35

import django.db.models.deletion
import product.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_no", models.TextField()),
                ("total_amount", models.PositiveIntegerField(blank=True, null=True)),
                ("paid_amount", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("Paid", "Paid"), ("Unpaid", "Unpaid")],
                        default="Unpaid",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=255)),
                (
                    "category_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=product.models.img_upload_path,
                        validators=[product.models.validate_img],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_type", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "item_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=product.models.img_upload_path,
                        validators=[product.models.validate_img],
                    ),
                ),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="product.menu"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order_Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "img",
                    models.ImageField(
                        blank=True, null=True, upload_to=product.models.img_upload_path
                    ),
                ),
                (
                    "table_no",
                    models.TextField(
                        choices=[
                            ("SELECT_TABLE_NO", "SELECT_TABLE_NO"),
                            ("TABLE: 1", "TABLE: 1"),
                            ("TABLE: 2", "TABLE: 2"),
                            ("TABLE: 3", "TABLE: 3"),
                            ("TABLE: 4", "TABLE: 4"),
                            ("TABLE: 5", "TABLE: 5"),
                            ("TABLE: 6", "TABLE: 6"),
                            ("TABLE: 7", "TABLE: 7"),
                            ("TABLE: 8", "TABLE: 8"),
                            ("TABLE: 9", "TABLE: 9"),
                            ("TABLE: 10", "TABLE: 10"),
                        ],
                        default="SELECT_TABLE_NO",
                    ),
                ),
                ("quantity", models.PositiveIntegerField(blank=True, null=True)),
                ("total_price", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "get_order",
                    models.TextField(
                        choices=[("ORDERED", "ORDERED"), ("WAITING", "WAITING")],
                        default="WAITING",
                    ),
                ),
                ("generated_by", models.CharField(max_length=255)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="product.menu"
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.menuitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=255)),
                (
                    "item_img",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=product.models.img_upload_path,
                        validators=[product.models.validate_img],
                    ),
                ),
                ("price", models.PositiveIntegerField()),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="product.menu"
                    ),
                ),
                (
                    "item_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.menuitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StockManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.PositiveIntegerField(blank=True, null=True)),
                ("quantity", models.PositiveIntegerField()),
                ("product_deduce", models.PositiveIntegerField()),
                ("now_available", models.PositiveBigIntegerField()),
                ("total_price", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "menu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="product.menu"
                    ),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.menuitem",
                    ),
                ),
                (
                    "product_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.productitem",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Tea_Items",
        ),
        migrations.AddField(
            model_name="bill",
            name="order_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.order_item"
            ),
        ),
        migrations.AddField(
            model_name="order_item",
            name="product_items",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="product.productitem"
            ),
        ),
    ]
