# Generated by Django 5.0.4 on 2024-07-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_alter_stockmanagement_now_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmanagement",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
