# Generated by Django 5.0.4 on 2024-07-03 13:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_alter_stockmanagement_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockmanagement",
            name="now_available",
        ),
        migrations.RemoveField(
            model_name="stockmanagement",
            name="product_deduce",
        ),
    ]
