# Generated by Django 5.0.4 on 2024-07-03 09:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
    ]
